FROM node:latest

ARG API_PORT
ARG UPLOADTHING_SECRET
ARG UPLOADTHING_APP_ID
ARG HOST
ARG PORT
ARG DATABASE
ARG USERNAME
ARG PASSWORD
ARG SYNCHRONIZE

ENV API_PORT $API_PORT
ENV UPLOADTHING_SECRET $UPLOADTHING_SECRET
ENV UPLOADTHING_APP_ID $UPLOADTHING_APP_ID
ENV HOST $HOST
ENV PORT $PORT
ENV DATABASE $DATABASE
ENV USERNAME $USERNAME
ENV PASSWORD $PASSWORD
ENV SYNCHRONIZE $SYNCHRONIZE

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

CMD [ "npm", "run", "start:dev" ]